In [1]:
import pandas as pd

pd.options.display.float_format = '{:,.2f}'.format

In [2]:
summary_billing_df = pd.read_csv("SUMMARY_BILLING_2023.csv")

In [3]:
summary_billing_df.dtypes

ACCOUNT_NO                 int64
TEL_NO                    object
PRODUCT DESC              object
ACCOUNT_TYPE              object
BANK_CODE                 object
CUSTOMER_REF              object
SERVICE_LOCATION NAME     object
INACTIVE_DATE             object
ACTIVE_DATE               object
AMOUNT_DUE               float64
dtype: object

In [4]:
summary_billing_df.head()

,ACCOUNT_NO,TEL_NO,PRODUCT DESC,ACCOUNT_TYPE,BANK_CODE,CUSTOMER_REF,SERVICE_LOCATION NAME,INACTIVE_DATE,ACTIVE_DATE,AMOUNT_DUE
0,100000876,022000030,N-ISDN - BAI,Corporate - Key Account (JorKorBor),D,1-KHM-0,ศูนย์บริการNT สุรวงศ์,2023-02-01,2011-03-11,"10,645.50"
1,100002342,022000364,N-ISDN - BAI,Corporate (CSC/YorTor),C,1-E3K-0,ศูนย์บริการ NT สุรวงศ์,2023-03-24,1998-02-20,"9,032.00"
2,100003110,022311925,Normal telephone,Business - Key Account (JorKorBor),C,1-YB-295,ศูนย์บริการ NT สุรวงศ์,2023-04-11,2021-10-01,"5,166.50"
3,100003110,022311925A,ADSL,Business - Key Account (JorKorBor),C,1-YB-295,ศูนย์บริการ NT สุรวงศ์,2023-04-11,2021-10-01,"25,316.50"
4,100003776,022000641,N-ISDN - BAI,Business - Key Account (JorKorBor),D,1-140-1433,ศูนย์บริการ NT สุรวงศ์,2023-03-21,2000-04-20,"7,097.00"

In [5]:
# Group by 'PRODUCT DESC' and sum 'AMOUNT_DUE'
product_due_sum = summary_billing_df.groupby('PRODUCT DESC')['AMOUNT_DUE'].sum().sort_values(ascending=False)
product_due_sum

PRODUCT DESC
Fiber 2U                       355,490,966.22
Normal telephone               348,649,603.21
IP Phone                       301,421,666.42
N-ISDN - PRI                    48,910,054.25
SIP Trunk                       23,842,005.83
IP Network                      13,404,484.00
ADSL                            11,972,732.00
Metro Lan                        5,889,032.00
NT Corporate Internet            2,874,000.00
ICT Solution                     1,393,871.00
Managed Service                    420,000.00
N-ISDN - BAI                       417,261.00
TOT IPTV[Units]                    410,527.50
Leased line - Digital Type 1       304,839.00
Broadband Wireless Access          201,070.00
Broadband Wireless net             137,551.00
PABX                                74,177.00
SPC VAS Product                     40,489.75
SPC Product                         36,288.00
TOT IPTV(n)                         26,473.00
IPSTAR telephone                    22,645.00
V-PBX                                9,237.50
nt NET PLAY iptv                     6,613.00
CloudApps                                0.00
Public Phone - Normal                    0.00
SBU Pay                                  0.00
C NEMA[Units]                            0.00
XXX                                      0.00
Name: AMOUNT_DUE, dtype: float64

In [6]:
# List of desired product descriptions
desired_products = ['Fiber 2U', 'IP Phone']
# Filter rows based on 'PRODUCT DESC' using boolean indexing
filtered_df = summary_billing_df[summary_billing_df['PRODUCT DESC'].isin(desired_products)]

In [7]:
filtered_df

,ACCOUNT_NO,TEL_NO,PRODUCT DESC,ACCOUNT_TYPE,BANK_CODE,CUSTOMER_REF,SERVICE_LOCATION NAME,INACTIVE_DATE,ACTIVE_DATE,AMOUNT_DUE
5,100007231,2246J9090,Fiber 2U,Residential - Normal,D,1-YB-690,ศูนย์บริการ NT อโศกดินแดง,2023-11-15,2020-11-26,"20,323.00"
6,100008300,2246J7204,Fiber 2U,Residential - Normal,D,1-YB-807,ศูนย์บริการ NT อโศกดินแดง,2023-11-15,2020-11-26,"20,323.00"
13,100025079,022041254,IP Phone,Residential - Normal,D,1-YE-378,ศูนย์บริการ NT สุขุมวิท 1,2023-11-19,2023-09-03,"14,722.00"
14,100025079,2252J1720,Fiber 2U,Residential - Normal,D,1-YE-378,ศูนย์บริการ NT สุขุมวิท 1,2023-11-19,2023-09-03,0.00
15,100027785,022041865,IP Phone,Residential - Normal,D,1-YE-794,ศูนย์บริการ NT สุขุมวิท 1,2024-08-25,2021-09-09,"44,596.67"
...,...,...,...,...,...,...,...,...,...,...
64813,104533366267,2373J4461,Fiber 2U,Residential - TOT Staff,D,CA-660901-0000304,ศูนย์บริการ NT รามคำแหง,2023-09-25,2023-09-12,"27,097.00"
64814,104533372796,7553J8286,Fiber 2U,Residential - Normal,D,CA-660920-0000477,ศูนย์บริการ NT สิชล,2023-11-29,2023-09-21,"20,800.00"
64817,104533378421,4357J9681,Fiber 2U,Residential - Normal,D,CA-660929-0000231,ศูนย์บริการ NT โพนทอง,2023-11-20,2023-09-06,"14,500.00"
64818,104533387006,038196519,IP Phone,Residential - Normal,D,CA-190001641259,ศูนย์บริการ NT พัทยา 1,2023-11-23,2023-10-11,"4,333.00"
64820,104533387262,3842J5452,Fiber 2U,Residential - Normal,D,1-2DQ77O,ศูนย์บริการ NT สัตหีบ 1,2023-10-24,2023-10-01,"37,935.00"

In [8]:
filtered_df.groupby(['ACCOUNT_TYPE', 'PRODUCT DESC'])['AMOUNT_DUE'].sum().sort_values(ascending=False)

ACCOUNT_TYPE                         PRODUCT DESC
Residential - Normal                 Fiber 2U       284,296,101.05
Business - SME (CSC/YorTor)          IP Phone       169,659,445.77
Residential - Normal                 IP Phone       112,309,118.50
Business - SME (CSC/YorTor)          Fiber 2U        57,240,651.67
Corporate - Key Account (JorKorBor)  IP Phone        10,356,166.08
                                     Fiber 2U         6,525,919.00
Corporate (CSC/YorTor)               IP Phone         5,097,921.90
Residential - Foreigner              Fiber 2U         2,763,841.00
Business - Key Account (JorKorBor)   IP Phone         1,958,504.50
                                     Fiber 2U         1,439,569.00
NPO                                  Fiber 2U         1,080,684.00
Government                           IP Phone           957,898.00
NPO                                  IP Phone           875,147.83
Government                           Fiber 2U           837,784.00
Residential - TOT Staff              Fiber 2U           655,220.00
Corporate (CSC/YorTor)               Fiber 2U           346,400.50
Residential - Monk                   Fiber 2U           248,925.00
High Ranking Govt Official           IP Phone            95,955.83
Residential - Foreigner              IP Phone            64,054.00
State Enterprise                     Fiber 2U            55,871.00
Residential - TOT Staff              IP Phone            37,132.00
State Enterprise                     IP Phone            10,322.00
High Ranking Govt Official           Fiber 2U                 0.00
Name: AMOUNT_DUE, dtype: float64

In [11]:
filtered_df.to_csv("Customer Group and Product Amount.csv", index=False, float_format="%.2f")

In [9]:
filtered_df.groupby(['ACCOUNT_TYPE'])['AMOUNT_DUE'].sum().sort_values(ascending=False)

ACCOUNT_TYPE
Residential - Normal                  396,605,219.55
Business - SME (CSC/YorTor)           226,900,097.43
Corporate - Key Account (JorKorBor)    16,882,085.08
Corporate (CSC/YorTor)                  5,444,322.40
Business - Key Account (JorKorBor)      3,398,073.50
Residential - Foreigner                 2,827,895.00
NPO                                     1,955,831.83
Government                              1,795,682.00
Residential - TOT Staff                   692,352.00
Residential - Monk                        248,925.00
High Ranking Govt Official                 95,955.83
State Enterprise                           66,193.00
Name: AMOUNT_DUE, dtype: float64

In [10]:
filtered_df[['ACCOUNT_TYPE', 'PRODUCT DESC']].value_counts().sort_values(ascending=False)

ACCOUNT_TYPE                         PRODUCT DESC
Residential - Normal                 Fiber 2U        11345
                                     IP Phone         8906
Business - SME (CSC/YorTor)          IP Phone         5706
                                     Fiber 2U         1465
Corporate - Key Account (JorKorBor)  IP Phone          785
Business - Key Account (JorKorBor)   IP Phone          168
Corporate (CSC/YorTor)               IP Phone          156
Corporate - Key Account (JorKorBor)  Fiber 2U          142
Residential - Foreigner              Fiber 2U           94
Business - Key Account (JorKorBor)   Fiber 2U           39
Residential - TOT Staff              Fiber 2U           37
NPO                                  IP Phone           36
Government                           Fiber 2U           28
                                     IP Phone           28
Corporate (CSC/YorTor)               Fiber 2U           23
NPO                                  Fiber 2U           21
High Ranking Govt Official           IP Phone           20
Residential - TOT Staff              IP Phone           12
Residential - Foreigner              IP Phone           10
Residential - Monk                   Fiber 2U            7
High Ranking Govt Official           Fiber 2U            7
State Enterprise                     Fiber 2U            4
                                     IP Phone            3
Name: count, dtype: int64